#!/usr/bin/env python3
"""
adams_df_boundfraction.py
=========================
Bound fraction after instantaneous gas expulsion computed directly from the
stellar distribution function, following the approach of Adams (2000) and
Boily & Kroupa (2003a), applied to our derived (Parmentier & Pfalzner 2013)
gas profiles.

Method
------
1. The isotropic stellar DF f(eps) is obtained by Eddington inversion of
   the stellar density rho_*(r) in the TOTAL (stars + gas) relative
   potential Psi_tot(r) (G = M_* = a = 1; Psi = -Phi, Phi(inf) = 0).
2. At gas expulsion the DF is frozen: every star keeps (r, v).
3. A star is bound iff v^2/2 < Psi_b(r), where Psi_b is the relative
   potential generated by the BOUND stars only. Since removing unbound
   stars shallows the potential and unbinds more stars, the criterion is
   iterated to convergence (positions held fixed; violent relaxation and
   recapture are neglected, cf. Sect. 5 caveats):
       rho_b(r) = 4 pi sqrt(2) int_{eps_min(r)}^{Psi_tot(r)}
                  f(eps) sqrt(Psi_tot - eps) d eps ,
       eps_min(r) = max(Psi_t, Psi_tot(r) - Psi_b(r)),
   where Psi_t = Psi_tot(r_t) for truncated (King) models and 0 otherwise.
4. F_bound = M_b / M_*; the DF-based critical SFE is where F_bound
   drops below F_MIN.

Verification built in:
  (a) pure Plummer inversion reproduces the analytic
      f(eps) = 24 sqrt(2)/(7 pi^3) eps^{7/2};
  (b) SFE = 1 (no gas) returns F_bound = 1;
  (c) identical-profile gas: the iterated criterion dissolves the cluster
      completely below SFE = 0.428 (King W0=6; 0.438 for Plummer).

VALIDATION AGAINST BOILY & KROUPA (2003a, MNRAS 338, 665 = Paper I)
-------------------------------------------------------------------
Their Eq. (7) is the scheme implemented here: the bound fraction at each
radius is the fraction of the local velocity distribution below the escape
speed of the stars alone, iterated by recomputing the potential from the
E <= 0 stars only.  For the Plummer sphere they solve it analytically and
find total dissolution below eps = 0.442201 with lambda_e = 0.509404 there.
Our numerical implementation gives 0.4376 (0.9 per cent low), and reproduces
their published bound-fraction curve (their Paper II, Table 1):

    SFE     0.80   0.70   0.60   0.55   0.50   0.45   0.40
    ours    0.998  0.989  0.955  0.914  0.838  0.645  0.000
    BK03a   0.99   0.99   0.95   0.92   0.85   0.69   0.00
    N-body  0.98   0.95   0.86   0.78   0.66   0.44   0.00

Two consequences worth keeping in mind:
  * the widely quoted "SFE > 1/3 for survival" is an N-BODY result with
    collisional effects (Lada et al. 1984; Geyer & Burkert 2001; Kroupa,
    Aarseth & Hurley 2001).  BK03b state explicitly that strictly
    collisionless evolution would give complete dissolution at eps = 0.33,
    the N-body survival there being due to two-body relaxation deepening
    the core during a finite expulsion time.  Our zeros below ~0.43 are
    therefore the correct collisionless answer, not a failure.
  * BK03b Sect. 4.3 introduce a modified scheme (their Eq. 13) tuned to
    match N-body for King models, by resetting the DF cut-off velocity to
    v_e^2 = 2(phi_star[E<0] + phi_gas).  Two readings of that prescription
    bracket their tabulated values rather than reproducing them, so it is
    NOT implemented here; the paper's DF numbers use the Paper I scheme
    above and are calibrated instead against the Monte Carlo runs of
    Sect. 5.  Paper I Table 1 lists polytrope thresholds for n > 5, but
    those models have infinite mass and extent and are not reproducible on
    a finite grid -- only the n = 5 (Plummer) entry is a valid check. This is EXPECTED and is the known bias of
      the frozen-DF estimate, not a failure:
        * the whole-system energy criterion gives E_tot > 0 for SFE < 0.5
          (identical profiles: T = |W_ss|/(2 SFE)), so the cluster as a whole
          is formally unbound below 0.5;
        * N-body with instantaneous expulsion nevertheless retains a remnant
          down to SFE ~ 1/3, because the escaping stars leave gradually and
          the survivors revirialize -- physics the frozen DF discards;
        * the SINGLE-PASS criterion (bound if v^2/2 < Psi_star, no iteration)
          errs the other way, giving F_b = 0.72 at SFE = 1/3.
      Single-pass and iterated therefore BRACKET the N-body answer
      (0.72 vs 0.00 at SFE = 1/3); this code deliberately uses the
      conservative (iterated) branch, and Sect. 5 of the paper quotes the
      Monte Carlo results, which inherit the same conservatism.
"""

import numpy as np
if not hasattr(np, 'trapezoid'):          # numpy < 2.0 compatibility
    np.trapezoid = np.trapz
from scipy.integrate import cumulative_trapezoid
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from matplotlib import cm, colors
import sys
sys.path.append('../01_king_sfe_analysis')
from king_sfe_analysis import king_model, gas_density
sys.path.append('../03_multi_profile_analysis')
from multi_profile_analysis import (plummer_model, dehnen_model,
                                    analyze_generic, tsf_for_threshold,
                                    critical_sfe_generic)

plt.rcParams.update({
    'font.size': 11, 'font.family': 'serif',
    'mathtext.fontset': 'dejavuserif',
    'axes.linewidth': 0.8, 'xtick.direction': 'in', 'ytick.direction': 'in',
    'xtick.top': True, 'ytick.right': True,
    'xtick.minor.visible': True, 'ytick.minor.visible': True,
    'legend.frameon': False, 'savefig.bbox': 'tight', 'savefig.dpi': 300,
})
OUTDIR = './'


def _mc_thresholds_from_csv(path, f_min=None):
    """Monte Carlo critical SFE per W0 from a per-realization CSV written by
    mc_bound_fraction_agama.py (columns: W0, SFE_target, SFE_actual, seed,
    F_bound, n_iter).

    For each W0 the realizations are grouped by SFE and the SURVIVAL FRACTION
    (share with F_bound > f_min) is formed; the threshold is where that crosses
    1/2, linearly interpolated between the bracketing SFE values, with half the
    gap quoted as the error. Survival probability rather than mean F_bound is
    used because near threshold the outcome is bimodal (Sect. 5), so the mean
    is not a meaningful centre.  Returns {W0: (SFE_crit, err)}; {} if absent.
    """
    if f_min is None:
        f_min = F_MIN
    if path is None:
        return {}
    d = np.loadtxt(path, delimiter=',', skiprows=1, ndmin=2)
    out = {}
    for w in np.unique(d[:, 0]):
        sub = d[d[:, 0] == w]
        sfes = np.unique(np.round(sub[:, 2], 6))
        surv = np.array([np.mean(sub[np.round(sub[:, 2], 6) == s, 4] > f_min)
                         for s in sfes])
        cross = None
        for i in range(1, len(sfes)):
            if surv[i - 1] < 0.5 <= surv[i]:
                cross = (sfes[i - 1], sfes[i], surv[i - 1], surv[i])
        if cross is None:
            continue
        s0, s1, p0, p1 = cross
        sc = s0 + (0.5 - p0) * (s1 - s0) / max(p1 - p0, 1e-12)
        out[float(w)] = (float(sc), float(0.5 * (s1 - s0)))
    return out


def _mc_thresholds_precomputed(path):
    """Read thresholds already reduced by mc_thresholds_n1e5.py.

    Columns: W0, SFE_thr, err_lo, err_hi, err_sym, grid_halfwidth, n_seeds.
    The symmetric bootstrap spread is returned as the error, so the value is a
    sampling uncertainty rather than the SFE-grid half-width that
    _mc_thresholds_from_csv can offer. Returns {W0: (SFE_thr, err)}; {} if the
    file is absent.
    """
    if path is None:
        return {}
    d = np.loadtxt(path, delimiter=',', skiprows=1, ndmin=2)
    return {float(r[0]): (float(r[1]), float(r[4])) for r in d}


def _find_csv(name):
    """Locate a CSV written by one of the sibling analysis scripts.
    Searches the working directory first, then sibling directories (the
    reproduction tree keeps each script in its own numbered folder), then the
    parent. Returns None if not found, so callers can degrade gracefully."""
    import glob, os
    for pat in (name, os.path.join('..', '*', name), os.path.join('..', name)):
        hits = sorted(glob.glob(pat))
        if hits:
            return hits[0]
    return None
F_MIN = 0.02          # bound fraction defining the DF-based threshold
# ----------------------------------------------------------------------
# EDDINGTON INVERSION. eddington_f_analytic() constructs d(rho)/dPsi and
# d^2(rho)/dPsi^2 analytically (see its docstring) rather than by chained
# finite differencing, which makes N_EPS a genuinely convergent quadrature
# resolution: raising it shrinks the reconstruction error monotonically
# (King W0=9: 9.8/3.6/1.3/0.46/0.16 per cent at N_EPS=500/1000/2000/4000/8000,
# with F_b stable to <0.02 per cent throughout).
# N_EPS=2000 is the default: typically 1-5 per cent reconstruction error at
# ~3x the per-call cost of N_EPS=1000. Raising it costs runtime linearly, so
# prefer the escalation ladder below over a global increase.
N_EPS = 2000

# bound_fraction() retries at increasing resolution whenever an evaluation
# fails ERR_TOL. Each rung is tried only for evaluations that failed the one
# before it: King W0<=6.5 and all of Plummer never leave the first rung, most
# of the rest resolves at 8000, and 32000 is reserved for the hardest cases
# (King W0>=14, Dehnen gamma=1 and 2, dense-scan W0>=11.5).
N_EPS_LADDER = (2000, 8000, 32000)
assert N_EPS_LADDER[0] == N_EPS, "N_EPS and N_EPS_LADDER[0] must match"

# ----------------------------------------------------------------------
# VALIDATION GATE: bound_fraction() self-checks by
# reconstructing rho_star from the just-inverted f(eps) at psi_cap=inf;
# ERR_TOL is the threshold on that reconstruction's max relative error (over
# the 1-95% mass shell) below which a DF evaluation is trusted. Every DF
# number this module produces ships with the 'err'/'valid' diagnostic that
# triggered it, in the printed tables and in the CSV outputs.
# ----------------------------------------------------------------------
ERR_TOL = 0.01         # max tolerated |rho_check - rho_star| / rho_star, 1-95% mass shell


def relative_potential(x, rho):
    """Psi(r) = G [ M(<r)/r + 4 pi int_r^rmax rho r dr ] on the grid x."""
    M = 4.0 * np.pi * cumulative_trapezoid(rho * x**2, x, initial=0.0)
    outer = 4.0 * np.pi * cumulative_trapezoid((rho * x)[::-1], x[::-1], initial=0.0)[::-1] * (-1.0)
    # note: integrating reversed grid gives negative dx; the (-1) restores sign
    return M / x + outer, M


def eddington_f_legacy(x, rho_s, psi_tot, psi_t, return_diag=False):
    """Finite-difference Eddington inversion. NOT for reported numbers --
    use eddington_f_analytic. Retained for bound_fraction_bk13 and for the
    accuracy comparison printed by verify().

    Inverts rho_*(Psi_tot) for eps in (psi_t, psi0], returning (eps_grid, f)
    with f(eps<=psi_t)=0 by construction. It takes two CHAINED finite-
    difference derivatives of a tabulated density, which is ill-conditioned:
    the second stencil's width is set by the N_EPS spacing, so N_EPS controls
    the estimator's noise/bias trade-off rather than just its sampling
    resolution. For cuspy profiles the reconstruction self-check in
    bound_fraction() can fail by many orders of magnitude as a result.

    f is clipped to max(f, 0) before returning, because bound_fraction()
    needs f>=0. A positivity test applied to the RETURNED f is therefore
    vacuous; pass return_diag=True for the pre-clip diagnostic
    {'neg_frac', 'worst_rel_negativity', 'clipped_any'}, which is what
    df_positivity_check.py inspects."""
    u = psi_tot - psi_t                      # shifted potential, >=0, decreasing in r
    keep = u > 0
    u_k, rho_k = u[keep][::-1], rho_s[keep][::-1]     # ascending in u
    uu, idx = np.unique(u_k, return_index=True)
    rr = rho_k[idx]
    # version-proof derivative + interpolation (avoid spline pathologies
    # observed on some numpy/scipy combinations): centered differences on
    # the nonuniform grid, linear interpolation for evaluation.
    drho_du = np.gradient(rr, uu)
    def dr_interp(u):
        return np.interp(u, uu, drho_du)

    q_grid = np.geomspace(1e-8 * uu[-1], uu[-1], N_EPS)  # q = eps - psi_t (log: resolves halo energies)
    # I(q) = int_0^q (drho/du) du / sqrt(q-u); substitute u = q - t^2
    I = np.empty_like(q_grid)
    for i, q in enumerate(q_grid):
        t = np.linspace(0.0, np.sqrt(q), 200)
        I[i] = 2.0 * np.trapezoid(dr_interp(np.clip(q - t**2, uu[0], uu[-1])), t)
    f_raw = np.gradient(I, q_grid) / (np.sqrt(8.0) * np.pi**2)
    f = np.maximum(f_raw, 0.0)
    if not return_diag:
        return psi_t + q_grid, f
    fmax = float(f.max()) if f.size else np.nan
    diag = {
        'neg_frac': float(np.mean(f_raw < 0.0)),
        'worst_rel_negativity': float(f_raw.min() / fmax) if fmax > 0 else np.nan,
        'clipped_any': bool(np.any(f_raw < 0.0)),
    }
    return psi_t + q_grid, f, diag


def eddington_f_analytic(model, rho_g, psi_t, return_diag=False, n_eps=None):
    """Eddington inversion of rho_star(Psi_tot), built WITHOUT differentiating
    any tabulated array. This is the inversion used for every reported number.

    The regularized Eddington formula needs d(rho)/dPsi and d^2(rho)/dPsi^2,
    not rho(Psi) itself:
        f(eps) = (1/sqrt(8) pi^2) [ int_0^eps (d^2 rho/dPsi^2) dPsi/sqrt(eps-Psi)
                                     + (1/sqrt(eps)) (d rho/dPsi)|_{Psi=0} ]
    Both derivatives are obtained by the CHAIN RULE THROUGH r, using pieces
    that are each already analytic or already-computed (no np.gradient of a
    density array anywhere):
      * rho_star'(r), rho_star''(r): analytic per profile family -- for King,
        rho_hat_prime/rho_hat_dprime(W) times dW/dr, d^2W/dr^2 read off the
        structure ODE's own state/RHS (king_model's rho1/rho2); for Plummer
        and Dehnen, elementary closed-form derivatives (plummer_model/
        dehnen_model's rho1/rho2). Model MUST carry rho1, rho2.
      * Psi_tot'(r) = -M_tot(r)/r^2 and Psi_tot''(r) = -4 pi rho_tot(r) +
        2 M_tot(r)/r^3: exact consequences of Gauss's law given the mass
        integral relative_potential() already computes -- algebra on
        already-known M_tot(r)/rho_tot(r), not a finite difference.
      * d(rho)/dPsi = rho1/Psi', d^2(rho)/dPsi^2 = (rho2 Psi' - rho1 Psi'')/Psi'^3.
    What remains is ONE well-posed numerical integral (a t^2-substitution
    quadrature fed an analytic integrand) -- no second differentiation, so
    N_EPS is a genuine quadrature resolution: raising it shrinks the
    reconstruction self-check error monotonically instead of moving the
    answer. See the N_EPS module comment above for the convergence numbers.

    Validated against the analytic pure-Plummer f(eps)=24 sqrt(2)/(7 pi^3)
    eps^3.5 to a max relative error of 5.8e-6; eddington_f_legacy reaches
    5.4e-4 on the same check. verify() prints both.

    return_diag=True adds the pre-clip diagnostic {'neg_frac',
    'worst_rel_negativity', 'clipped_any'}; f itself is clipped at zero.

    n_eps overrides the module-level N_EPS for this call only (used by
    bound_fraction's N_EPS escalation ladder, see N_EPS_LADDER above)."""
    n_eps = N_EPS if n_eps is None else n_eps
    x, rho_s, rho1, rho2 = model['x'], model['rho'], model['rho1'], model['rho2']
    rho_tot = rho_s + rho_g
    psi_tot, M_tot = relative_potential(x, rho_tot)
    with np.errstate(divide='ignore', invalid='ignore'):
        psi1 = -M_tot / x**2                                    # Psi_tot'(r)
        psi2 = -4.0 * np.pi * rho_tot + 2.0 * M_tot / x**3       # Psi_tot''(r)
        drho_dpsi = rho1 / psi1
        d2rho_dpsi2 = (rho2 * psi1 - rho1 * psi2) / psi1**3
    # psi1 -> 0 at r -> 0 (M_tot ~ r^3 there) makes the two ratios above a
    # literal 0/0 at the innermost grid point or two; those are dropped, not
    # patched -- the interpolation below only needs values on a grid dense
    # enough that a couple of edge points cost nothing.
    u = psi_tot - psi_t                      # shifted potential, >=0, decreasing in r
    keep = (u > 0) & np.isfinite(d2rho_dpsi2) & np.isfinite(drho_dpsi)
    order = np.argsort(u[keep])              # ascending in u
    u_k = u[keep][order]
    d2_k, d1_k = d2rho_dpsi2[keep][order], drho_dpsi[keep][order]
    uu, idx = np.unique(u_k, return_index=True)
    d2u, d1u = d2_k[idx], d1_k[idx]
    def d2_interp(u):
        return np.interp(u, uu, d2u)

    q_grid = np.geomspace(1e-8 * uu[-1], uu[-1], n_eps)  # q = eps - psi_t (log: resolves halo energies)
    # I(q) = int_0^q (d^2 rho/dPsi^2) du/sqrt(q-u); substitute u = q - t^2
    I = np.empty_like(q_grid)
    for i, q in enumerate(q_grid):
        t = np.linspace(0.0, np.sqrt(q), 200)
        I[i] = 2.0 * np.trapezoid(d2_interp(np.clip(q - t**2, uu[0], uu[-1])), t)
    # boundary term (drho/dPsi)|_{Psi=0}: uu[0] is the smallest tabulated
    # shifted potential, i.e. the outer edge of the model (r=r_t for
    # truncated/King, r=rmax for infinite-extent Plummer/Dehnen on their
    # finite numerical grid) -- the practical Psi=0 reference in both cases.
    boundary = d1u[0] / np.sqrt(q_grid)
    f_raw = (I + boundary) / (np.sqrt(8.0) * np.pi**2)
    f = np.maximum(f_raw, 0.0)
    if not return_diag:
        return psi_t + q_grid, f
    fmax = float(f.max()) if f.size else np.nan
    diag = {
        'neg_frac': float(np.mean(f_raw < 0.0)),
        'worst_rel_negativity': float(f_raw.min() / fmax) if fmax > 0 else np.nan,
        'clipped_any': bool(np.any(f_raw < 0.0)),
    }
    return psi_t + q_grid, f, diag


def bound_fraction_bk13(model, rho_g, n_iter=80, tol=1e-6):
    """Boily & Kroupa (2003a) 'improved' scheme, their Eq. (13).

    Difference from the plain iterated criterion: the bound stars are treated
    as a SELF-GRAVITATING group that revirializes on a timescale short
    compared with the escape of the unbound ones. Practically, at each
    iteration the distribution function is re-derived by Eddington inversion
    of the CURRENT bound density in the CURRENT bound potential, instead of
    reusing the frozen initial DF. BK03b found this reproduces their N-body
    bound fractions for concentrated King models, where the plain scheme does
    not (their Fig. 3a).
    """
    x, rho_s = model['x'], model['rho']
    psi_tot, _ = relative_potential(x, rho_s + rho_g)
    psi_star, M_s = relative_potential(x, rho_s)
    psi_t = psi_tot[-1] if np.isfinite(model.get('rt', np.inf)) else 0.0

    rho_b = rho_s.copy()
    F_old = 1.0
    for _ in range(n_iter):
        psi_b, M_b = relative_potential(x, rho_b)
        # DF of the current bound population in its own potential
        eps, f = eddington_f_legacy(x, rho_b, psi_b + psi_tot - psi_star, psi_t)
        psi_eff = psi_b + psi_tot - psi_star      # bound stars + (unchanged) gas
        E = eps[None, :]
        PT = psi_eff[:, None]
        EM = np.maximum(psi_t, psi_eff - psi_b)[:, None]
        w = np.where((E >= EM) & (E <= PT),
                     f[None, :] * np.sqrt(np.maximum(PT - E, 0.0)), 0.0)
        rho_new = 4.0 * np.pi * np.sqrt(2.0) * np.trapezoid(w, eps, axis=1)
        rho_b = np.minimum(np.maximum(rho_new, 0.0), rho_s)
        F = relative_potential(x, rho_b)[1][-1]
        if abs(F - F_old) < tol:
            break
        F_old = F
    return F, np.nan


def _bound_fraction_at(model, rho_g, n_eps, n_iter=60, tol=1e-6):
    """bound_fraction's actual computation at a fixed N_EPS. See
    bound_fraction (below) for the public entry point, which adds automatic
    N_EPS escalation on top of this."""
    x, rho_s = model['x'], model['rho']
    psi_tot, _ = relative_potential(x, rho_s + rho_g)
    psi_star, M_s = relative_potential(x, rho_s)
    psi_t = psi_tot[-1] if np.isfinite(model.get('rt', np.inf)) else 0.0

    eps, f = eddington_f_analytic(model, rho_g, psi_t, n_eps=n_eps)

    # rho from the frozen DF given a cap: rho(r) = 4 pi sqrt2 *
    #   int_{eps_min}^{psi_tot} f sqrt(psi_tot - eps) d eps
    def df_density(psi_cap):
        eps_min = np.maximum(psi_t, psi_tot - psi_cap)
        E = eps[None, :]                       # (1, N_EPS)
        PT = psi_tot[:, None]
        EM = eps_min[:, None]
        w = np.where((E >= EM) & (E <= PT), f[None, :] * np.sqrt(np.maximum(PT - E, 0.0)), 0.0)
        return 4.0 * np.pi * np.sqrt(2.0) * np.trapezoid(w, eps, axis=1)

    # consistency: full cap must reproduce rho_s; the pointwise ratio
    # rho_s/rho_check is then applied as a correction factor to cancel the
    # numerical error of the inversion systematically (essential for the
    # infinite-halo models, where uncorrected outer errors otherwise feed a
    # runaway of spurious bound mass through the iteration).
    rho_check = df_density(np.full_like(x, np.inf))
    sel = (M_s > 0.01) & (M_s < 0.95)
    err = float(np.max(np.abs(rho_check - rho_s)[sel] / np.maximum(rho_s, 1e-12)[sel]))
    corr_raw = np.where(rho_check > 0, rho_s / np.maximum(rho_check, 1e-300), 0.0)
    corr = np.clip(corr_raw, 0.0, 2.0)

    psi_b = psi_star.copy()
    F_old = 1.0
    converged = False
    n_used = 0
    for it in range(n_iter):
        rho_b = np.minimum(df_density(psi_b) * corr, rho_s)  # bound subset <= total
        psi_b, M_b = relative_potential(x, rho_b)
        F = M_b[-1]
        n_used = it + 1
        if abs(F - F_old) < tol:
            converged = True
            break
        F_old = F

    diag = {
        'err': err, 'valid': err <= ERR_TOL, 'n_eps': n_eps,
        'corr_min': float(corr_raw[sel].min()), 'corr_max': float(corr_raw[sel].max()),
        'clipped': bool(np.any((corr_raw[sel] < 0.0) | (corr_raw[sel] > 2.0))),
        'n_iter': n_used, 'converged': converged,
    }
    return F, diag


def bound_fraction(model, rho_g, n_iter=60, tol=1e-6):
    """Iterated escape-criterion bound fraction for a model + gas profile.

    Evaluates at N_EPS_LADDER[0] (the module default); if that fails the
    ERR_TOL reconstruction check, retries at each successive rung
    (8000, then 32000) until one passes or the ladder runs out, keeping
    only the last attempt made. Each rung is tried only for evaluations
    that failed the one before it -- most of the pipeline (King W0<=6.5,
    all of Plummer) never leaves the default, and most of the rest resolves
    by 8000; 32000 is reserved for whatever is still failing after that.

    Returns (F, diag). diag is the validation-gate record (see ERR_TOL above):
      err       max |rho_check - rho_star| / rho_star over the 1-95% mass
                shell -- the reconstruction self-consistency check.
      valid     err <= ERR_TOL. False means this evaluation is NOT trusted
                even after the full ladder; F is still returned (nothing is
                hidden), but callers/CSVs/figures should flag it rather than
                quote it silently.
      n_eps     the N_EPS this result actually used -- so every number can
                be traced back to the resolution that produced it.
      escalated True if N_EPS_LADDER[0] failed and this is a retry at a
                higher rung (whether or not the retry itself passed);
                False means the default sufficed.
      corr_min, corr_max   the raw (pre-clip) correction ratio rho_star/
                rho_check over the same shell -- how far off the inversion
                was before the [0,2] clip papered over it.
      clipped   True if the raw ratio left [0,2] anywhere on the shell, i.e.
                the clip is doing more than rounding error -- the applied
                correction cannot cancel the calibration case.
      n_iter, converged   escape-criterion iteration count actually used and
                whether |F-F_old|<tol was reached before n_iter ran out.
    """
    F, diag = _bound_fraction_at(model, rho_g, N_EPS_LADDER[0], n_iter, tol)
    diag['escalated'] = False
    if diag['valid']:
        return F, diag
    for n_eps in N_EPS_LADDER[1:]:
        prev_err = diag['err']
        F, diag = _bound_fraction_at(model, rho_g, n_eps, n_iter, tol)
        diag['escalated'] = True
        diag['err_at_previous_n_eps'] = prev_err   # this rung's predecessor, not necessarily N_EPS_LADDER[0]
        if diag['valid']:
            break
    return F, diag


def fbound_curve(model, tsf_grid, refine=True, f_min=F_MIN, n_ref=6):
    """F_bound(SFE) sweep; if refine, adds n_ref extra tsf points around the
    F = f_min crossing to reduce interpolation error in the threshold.
    Returns (sfes, Fs, valids) -- valids flags each point's reconstruction
    self-check (see ERR_TOL doc above); unused elsewhere in this module but
    kept in the public interface for the same reason the check exists."""
    tsf = list(tsf_grid)
    sfes, Fs, valids = [], [], []
    for t in tsf:
        res = analyze_generic(model, t)
        F, diag = bound_fraction(model, res['rho_g'])
        sfes.append(res['sfe_total'])
        Fs.append(F)
        valids.append(diag['valid'])
    if refine:
        o = np.argsort(sfes)
        Fv = np.array(Fs)[o]
        ts = np.array(tsf)[o]
        ic = np.where(Fv >= f_min)[0]
        if len(ic) and ic[0] > 0:
            lo, hi = ts[ic[0] - 1], ts[ic[0]]
            for t in np.geomspace(lo, hi, n_ref + 2)[1:-1]:
                res = analyze_generic(model, t)
                F, diag = bound_fraction(model, res['rho_g'])
                sfes.append(res['sfe_total'])
                Fs.append(F)
                valids.append(diag['valid'])
    return np.array(sfes), np.array(Fs), np.array(valids)


def fbound_at_sfe(model, sfe, convention='total', return_diag=False):
    """F_bound at a fixed global SFE: inverts SFE -> t_sf for THIS model
    (cheap, gas-mass integrals only), then evaluates the DF bound fraction.
    This keeps different-W0 models comparable at identical SFE points,
    unlike sweeping a common t_sf grid, which samples each model's F(SFE)
    curve in different places.

    return_diag=True also returns the bound_fraction validation diagnostic
    (err/valid/corr_min/corr_max/clipped/n_iter/converged); default False
    keeps the plain-float return every pre-existing caller relies on."""
    tsf = tsf_for_threshold(model, sfe, convention)
    res = analyze_generic(model, tsf)
    F, diag = bound_fraction(model, res['rho_g'])
    return (F, diag) if return_diag else F


def threshold_by_bisection(model, f_min=F_MIN, sfe_lo=0.003, sfe_hi=0.6,
                           n_scan=7, n_bisect=7, convention='total'):
    """DF-based critical SFE via direct bisection in SFE space.
    Coarse log scan brackets the F = f_min crossing, then bisection
    refines it; ~n_scan + n_bisect expensive evaluations per model.

    Returns (sc, scan, Fs, diag). The root-finding itself is UNCHANGED (same
    last-crossing scan + bisection as before); diag just records how much to
    trust the answer it produced -- diag['worst_err'] is the largest
    reconstruction-check error (see ERR_TOL doc above) among every evaluation
    that actually determined sc (the bracketing scan pair plus every
    bisection midpoint), and diag['valid'] = worst_err <= ERR_TOL. A caller
    that gets valid=False should treat sc as unreliable and say so, not
    discard it silently -- the raw number and its error are both in diag."""
    scan = np.geomspace(sfe_lo, sfe_hi, n_scan)
    evals = [fbound_at_sfe(model, s, convention, return_diag=True) for s in scan]
    Fs = np.array([F for F, _ in evals])
    scan_errs = np.array([d['err'] for _, d in evals])
    any_escalated = any(d['escalated'] for _, d in evals)
    lo = hi = lo_i = hi_i = None
    for i in range(1, n_scan):
        if Fs[i - 1] < f_min <= Fs[i]:
            lo, hi = scan[i - 1], scan[i]
            lo_i, hi_i = i - 1, i
    if lo is None:
        diag = {'worst_err': np.nan, 'valid': False, 'scan_errs': scan_errs,
                'any_escalated': any_escalated}
        return (np.nan, scan, Fs, diag)
    worst_err = max(scan_errs[lo_i], scan_errs[hi_i])
    for _ in range(n_bisect):
        mid = np.sqrt(lo * hi)
        Fm, dm = fbound_at_sfe(model, mid, convention, return_diag=True)
        worst_err = max(worst_err, dm['err'])
        any_escalated = any_escalated or dm['escalated']
        if Fm < f_min:
            lo = mid
        else:
            hi = mid
    diag = {'worst_err': worst_err, 'valid': worst_err <= ERR_TOL,
            'scan_errs': scan_errs, 'any_escalated': any_escalated}
    return (np.sqrt(lo * hi), scan, Fs, diag)


# ----------------------------------------------------------------------
def verify():
    print("Verification:")
    # (a) Plummer analytic DF -- primary check against eddington_f_analytic
    # (the method bound_fraction actually uses), plus a printed comparison
    # against eddington_f_legacy, which quantifies why the analytic
    # inversion is used for reported numbers (see
    # docs/feedback-2026-09.md).
    m = plummer_model(rmin=1e-4, rmax=1e3, n=4000)
    psi, _ = relative_potential(m['x'], m['rho'])
    f_true_fn = lambda e: 24.0 * np.sqrt(2.0) / (7.0 * np.pi**3) * e**3.5

    eps_a, f_a = eddington_f_analytic(m, np.zeros_like(m['rho']), 0.0)
    sel_a = (eps_a > 0.1) & (eps_a < 0.9)
    err_a = np.max(np.abs(f_a[sel_a] - f_true_fn(eps_a[sel_a])) / f_true_fn(eps_a[sel_a]))
    print(f"  (a) Plummer Eddington inversion vs analytic: max rel err = {err_a:.2e}  (analytic method)")
    if err_a >= 0.02:
        import scipy
        print(f"      FAILED. numpy {np.__version__}, scipy {scipy.__version__}")
        print("      eps, f_numeric, f_analytic (sample):")
        for e in (0.15, 0.3, 0.5, 0.7, 0.85):
            j = np.argmin(np.abs(eps_a - e))
            print(f"        {eps_a[j]:.3f}  {f_a[j]:.4e}  {f_true_fn(eps_a[j]):.4e}")
        raise AssertionError("Eddington inversion verification failed -- "
                             "please send the above diagnostic output")
    eps_l, f_l = eddington_f_legacy(m['x'], m['rho'], psi, 0.0)
    sel_l = (eps_l > 0.1) & (eps_l < 0.9)
    err_l = np.max(np.abs(f_l[sel_l] - f_true_fn(eps_l[sel_l])) / f_true_fn(eps_l[sel_l]))
    print(f"      (for comparison, eddington_f_legacy on the same check: {err_l:.2e})")

    # (b) no gas -> F = 1
    mk = king_model(6.0)
    F, diag = bound_fraction(mk, np.zeros_like(mk['rho']))
    print(f"  (b) King W0=6, no gas: F_bound = {F:.4f} "
          f"(DF density check err {diag['err']:.1e}, {'OK' if diag['valid'] else 'FAILS ERR_TOL'})")
    assert abs(F - 1.0) < 5e-3

    # (c) identical-profile gas: complete dissolution below SFE = 0.428
    #     (see the module docstring -- conservative by construction)
    for sfe in (0.5, 0.45, 0.4, 1.0 / 3.0):
        rho_g = mk['rho'] * (1.0 - sfe) / sfe
        F, diag = bound_fraction(mk, rho_g)
        flag = '' if sfe > 0.428 else '   <- below the frozen-DF threshold (0.428)'
        bad = '' if diag['valid'] else f"   [reconstruction err {diag['err']:.1e} > ERR_TOL]"
        print(f"  (c) identical profiles, SFE={sfe:.3f}: F_bound = {F:.4f}{flag}{bad}")
    print("      (the frozen-DF estimate dissolves identical-profile clusters "
          "below SFE=0.428,\n       vs ~1/3 in N-body: conservative by "
          "construction -- see module docstring)")


def main():
    verify()

    # ------- Fig 10: F_bound(SFE) for the King family -------------------
    # Fixed SFE grid, identical for every W0 (inverted to t_sf per model),
    # so the curves are directly comparable; thresholds by SFE-bisection.
    print("\nF_bound curves (fixed-SFE evaluation):")
    # Sampling: uniform 2 per cent steps (0.02 ... 0.60) plus three finer
    # points at 0.005/0.01/0.015 for the most concentrated models, whose
    # thresholds are below 0.02.
    #
    # The threshold is found FIRST (bisection, ~14 evaluations), and the curve
    # is then sampled only from just below it upwards: below threshold every
    # model has F_b = 0 identically, so evaluating there is pure cost. Two
    # probe points are kept below the threshold to show the curve leaving
    # zero. For W0 = 0.5 (threshold 0.35) this skips ~17 of 33 points.
    BASE_GRID = np.concatenate([[0.005, 0.01, 0.015],
                                np.round(np.arange(0.02, 0.6001, 0.02), 4)])
    N_BELOW = 2                       # probe points retained below threshold
    W0_family = np.array([0.5, 2, 4, 6, 8, 9, 10, 12, 14, 16, 18, 20])
    norm = colors.Normalize(vmin=W0_family.min(), vmax=W0_family.max())
    cmap = cm.viridis
    fig, ax = plt.subplots(figsize=(4.6, 3.7))
    crit_rows = []
    crit_diag = []                    # (worst_err, valid) per row, same order
    fig10_rows = []                   # kind, x, SFE, F_b  (kind 0 = King, x = W0)
    n_eval_total, n_full_total = 0, 0
    n_invalid = 0
    for w in W0_family:
        m = king_model(w)
        sc, _, _, diag = threshold_by_bisection(m)
        crit_rows.append([w, sc])
        crit_diag.append((diag['worst_err'], diag['valid']))
        below = BASE_GRID[BASE_GRID < sc]
        grid = np.concatenate([below[-N_BELOW:], BASE_GRID[BASE_GRID >= sc]])
        F = np.array([fbound_at_sfe(m, s) for s in grid])
        gs = np.concatenate([[0.0], grid]); fs = np.concatenate([[0.0], F])
        fig10_rows += [[0, w, s, f] for s, f in zip(gs, fs)]
        # the curve is identically zero below the first sampled point
        ax.plot(gs, fs, color=cmap(norm(w)), lw=1.4)
        if not diag['valid']:
            ax.plot(sc, F_MIN, '*', color='k', ms=9, mew=0.8, zorder=9)
            n_invalid += 1
        n_eval_total += grid.size
        n_full_total += BASE_GRID.size
        flag = '' if diag['valid'] else f"  ** RECONSTRUCTION CHECK FAILED (err={diag['worst_err']:.2e} > {ERR_TOL:.0%}) **"
        print(f"  W0={w:5.1f}: SFE_crit(DF, F<{F_MIN}) = {sc:.4f}"
              f"   [{grid.size}/{BASE_GRID.size} grid points evaluated]{flag}")
    print(f"  total curve evaluations: {n_eval_total} of {n_full_total} "
          f"({100 * (1 - n_eval_total / n_full_total):.0f}% saved)")
    if n_invalid:
        print(f"  ({n_invalid}/{len(W0_family)} King thresholds above marked 'x' on "
              f"Fig 10 failed the ERR_TOL={ERR_TOL:.0%} reconstruction check -- "
              "see the console flags above and df_threshold_summary.csv.")

    # Overlay the published families (dashed, separate palette -- same
    # convention as the cross-profile figures of multi_profile_analysis.py).
    # The point is the SHAPE: diffuse profiles switch on abruptly, while
    # concentrated/cuspy ones rise slowly, i.e. they survive as a small dense
    # seed over a wide range of SFE rather than surviving intact.
    pal_pub = {'Plummer': '#000000', 'Dehnen $\\gamma=0$': '#e08214',
               'Dehnen $\\gamma=1$': '#807dba', 'Dehnen $\\gamma=2$': '#8c510a'}
    pub_families = [('Plummer', plummer_model()),
                    ('Dehnen $\\gamma=0$', dehnen_model(0.0)),
                    ('Dehnen $\\gamma=1$', dehnen_model(1.0)),
                    ('Dehnen $\\gamma=2$', dehnen_model(2.0))]
    pub_thresholds = {}                      # frozen-DF (continuum)
    # published N-body survival thresholds; the two Dehnen cusps are the
    # lowest SIMULATED SFE that survived, i.e. upper limits (marked 'v').
    pub_nbody = {'Plummer': (0.150, False), 'Dehnen $\\gamma=0$': (0.090, False),
                 'Dehnen $\\gamma=1$': (0.0241, True), 'Dehnen $\\gamma=2$': (0.0148, True)}
    pub_virial = {}                          # virial criterion, eSFE_c = 1/3
    # local import: keeps this block working regardless of how the module
    # header imports multi_profile_analysis (paths differ between layouts)
    from multi_profile_analysis import critical_sfe_generic
    pub_diag = {}                      # {label: (worst_err, valid)}
    print("\n  published families (dashed in Fig. 10):")
    for lab, m in pub_families:
        sc, _, _, diag = threshold_by_bisection(m, convention='ap10')
        pub_thresholds[lab] = sc
        pub_diag[lab] = (diag['worst_err'], diag['valid'])
        # imported here rather than at module level: user setups that edit
        # the top-of-file import block would otherwise miss this name
        from multi_profile_analysis import critical_sfe_generic
        pub_virial[lab] = critical_sfe_generic(m, 1.0 / 3.0, 'ap10')
        below = BASE_GRID[BASE_GRID < sc]
        grid = np.concatenate([below[-N_BELOW:], BASE_GRID[BASE_GRID >= sc]])
        F = np.array([fbound_at_sfe(m, s, convention='ap10') for s in grid])
        gs = np.concatenate([[0.0], grid]); fs = np.concatenate([[0.0], F])
        kind = {'Plummer': 1, 'Dehnen $\\gamma=0$': 2,
                'Dehnen $\\gamma=1$': 3, 'Dehnen $\\gamma=2$': 4}[lab]
        fig10_rows += [[kind, np.nan, s, f] for s, f in zip(gs, fs)]
        ax.plot(gs, fs, color=pal_pub[lab], lw=1.3, ls='--')
        f2 = float(np.interp(2.0 * sc, grid, F))
        flag = '' if diag['valid'] else f"  ** RECONSTRUCTION CHECK FAILED (err={diag['worst_err']:.2e}) **"
        print(f"    {lab.replace('$','').replace(chr(92)+'gamma','g'):<16}"
              f"SFE_crit(DF)={sc:.4f}   F_b(2 x SFE_crit)={f2:.3f}{flag}")
    for lab in pal_pub:
        ax.plot([], [], color=pal_pub[lab], lw=1.3, ls='--', label=lab)
    if n_invalid:
        ax.plot([], [], '*', color='k', ms=8, mew=0.8, ls='none',
                label=fr'DF reconstr. check failed ($>${ERR_TOL:.0%})')
    ax.legend(fontsize=7, loc='lower right')
    fig.colorbar(cm.ScalarMappable(norm=norm, cmap=cmap), ax=ax, label=r'$W_0$')
    ax.axhline(F_MIN, color='0.6', ls=':', lw=1)
    ax.set(xlabel='global SFE', ylabel=r'bound fraction $F_{\rm b}$ (DF estimate)',
           xlim=(0, 0.62), ylim=(0, 1.02))
    fig.savefig(OUTDIR + 'fig10_fbound_curves.pdf')
    fig.savefig(OUTDIR + 'fig10_fbound_curves.png')
    plt.close(fig)
    crit_rows = np.array(crit_rows)
    crit_valid = dict(zip(W0_family, [v for _, v in crit_diag]))  # for Fig 11 markers

    # ------- published-threshold comparison ------------------------------
    print("\nAt published thresholds (F_bound predicted by the frozen-DF estimate):")
    for label, ctor, conv, thr in [
            ('Plummer', plummer_model, 'ap10', 0.15),
            ('Dehnen g=0', lambda: dehnen_model(0.0), 'ap10', 0.09),
            ('Dehnen g=1', lambda: dehnen_model(1.0), 'ap10', 0.025),
            ('Dehnen g=2', lambda: dehnen_model(2.0), 'ap10', 0.013)]:
        m = ctor()
        tsf = tsf_for_threshold(m, thr, conv)
        res = analyze_generic(m, tsf)
        F, diag = bound_fraction(m, res['rho_g'])
        flag = '' if diag['valid'] else f"  ** RECONSTRUCTION CHECK FAILED (err={diag['err']:.2e}) **"
        print(f"  {label:<12} SFE_thr={thr:.3f}: F_bound(DF) = {F:.4f}{flag}")

    # ------- DF-based critical SFE for the published families ------------
    # Same bisection as for the King family, so the two are directly
    # comparable. The frozen-DF estimate neglects recapture and
    # revirialization, so it is expected to be CONSERVATIVE (higher threshold)
    # for these diffuse profiles; quantifying that gap is the point.
    # NOTE: the Eddington inversion this relies on is a chained
    # finite-difference derivative (see eddington_f docstring) and is not
    # proven convergent for cuspy/infinite-extent profiles. worst_err/valid
    # below are the ERR_TOL reconstruction gate (see its doc above); a Dehnen
    # row with valid=False means DO NOT quote SFE_crit_DF for it -- the
    # bisection still ran and a number is reported (nothing hidden), but the
    # self-consistency check that would justify trusting it failed, in some
    # cases by many orders of magnitude.
    print("\nDF-based critical SFE for the published families:")
    print(f"  {'model':<14}{'SFE_crit(DF)':>14}{'published':>11}{'ratio':>8}"
          f"{'worst_err':>12}  valid")
    pub_rows = []
    for label, ctor, conv, thr in [
            ('Plummer', plummer_model, 'ap10', 0.150),
            ('Dehnen g=0', lambda: dehnen_model(0.0), 'ap10', 0.090),
            ('Dehnen g=1', lambda: dehnen_model(1.0), 'ap10', 0.0241),
            ('Dehnen g=2', lambda: dehnen_model(2.0), 'ap10', 0.0148)]:
        m = ctor()
        sc, _, _, diag = threshold_by_bisection(m, convention=conv)
        pub_rows.append([sc, thr, diag['worst_err'], float(diag['valid'])])
        print(f"  {label:<14}{sc:>14.4f}{thr:>11.4f}"
              f"{(sc / thr if np.isfinite(sc) else np.nan):>8.2f}"
              f"{diag['worst_err']:>12.2e}  {'OK' if diag['valid'] else '** FAIL **'}")
    np.savetxt(OUTDIR + 'df_threshold_published_families.csv',
               np.array(pub_rows), fmt='%.6f', delimiter=', ',
               header='SFE_crit_DF, SFE_thr_published, worst_err, valid', comments='')

    # ------- Fig 11: DF threshold vs eta-based threshold -----------------
    eta_path = _find_csv('mechanism_summary.csv')
    if eta_path is None:
        print("  (mechanism_summary.csv not found -- run king_sfe_mechanism.py "
              "for the virial curve; plotting the DF curve alone)")
        eta_rows = None
    else:
        eta_rows = np.loadtxt(eta_path, delimiter=',', skiprows=1)

    # Monte Carlo thresholds (frozen DF, N = 1e5, 50 realizations). King values
    # measured with mc_bound_fraction_agama.py; published-family values are
    # read from mc_thresholds_published.csv if that run has been done.
    # Prefer the N=1e5 thresholds with bootstrap errors (mc_thresholds_n1e5.py)
    # over re-deriving them from a per-realization CSV, which yields only an
    # SFE-grid half-width. Falls back to the per-realization route if absent.
    mc_king = _mc_thresholds_precomputed(_find_csv('mc_thresholds_n1e5.csv'))
    if not mc_king:
        mc_king = _mc_thresholds_from_csv(_find_csv('mc_bound_fractions.csv'))
    mc_pub_path = _find_csv('mc_thresholds_published.csv')
    mc_pub = {}
    if mc_pub_path is not None:
        for row in np.loadtxt(mc_pub_path, delimiter=',', skiprows=1, ndmin=2):
            mc_pub[['Plummer', 'Dehnen $\\gamma=0$', 'Dehnen $\\gamma=1$',
                    'Dehnen $\\gamma=2$'][int(row[0])]] = (row[1], row[2])

    crit_rows = np.array(crit_rows)

    # ---- save every plotted quantity, so fig10/fig11/fig11b can be
    #      re-drawn with cosmetic changes WITHOUT re-running the DF sweep.
    #      plot_df_figures.py reads these two files (+ the committed MC CSVs);
    #      it never touches king_model, fbound_at_sfe or any DF machinery.
    np.savetxt(OUTDIR + 'fig10_fbound_curves.csv', np.array(fig10_rows),
               fmt='%.6f', delimiter=', ',
               header='kind(0=King;1=Plummer;2..4=Dehnen g=0/1/2), '
                      'W0(NaN for published), SFE, F_b', comments='')

    _pub_ord = {'Plummer': -1.0, 'Dehnen $\\gamma=0$': -2.0,
                'Dehnen $\\gamma=1$': -3.0, 'Dehnen $\\gamma=2$': -4.0}
    _nan = float('nan')
    _eta = eta_rows if eta_rows is not None else np.empty((0, 2))
    def _vir_at(w):
        return (float(np.interp(w, _eta[:, 0], _eta[:, 1]))
                if _eta.shape[0] else _nan)
    p11 = []
    for w0, vir in _eta[:, :2]:                           # virial curve
        p11.append([0, w0, vir, _nan, _nan, _nan, _nan, _nan, _nan])
    for (w0, sc), (we, vv) in zip(crit_rows, crit_diag):  # DF continuum curve
        p11.append([1, w0, _nan, sc, _nan, _nan, _nan, _nan, float(vv)])
    for w in (3.0, 6.0, 9.0, 12.0):                       # King discrete points
        vir = _vir_at(w)
        dfc = float(np.interp(w, crit_rows[:, 0], crit_rows[:, 1]))
        mv, me = mc_king.get(w, (_nan, _nan))
        p11.append([2, w, vir, dfc, mv, me, _nan, _nan,
                    float(crit_valid.get(w, 1.0))])
    for lab, xo in _pub_ord.items():                      # published-family strip
        mv, me = mc_pub.get(lab, (_nan, _nan))
        nb, cens = pub_nbody[lab]
        p11.append([3, xo, pub_virial[lab], pub_thresholds[lab], mv, me,
                    nb, float(cens), float(pub_diag[lab][1])])
    np.savetxt(OUTDIR + 'fig11_plotdata.csv', np.array(p11, dtype=float),
               fmt='%.6f', delimiter=', ',
               header='series(0=virial_curve;1=dfcont_curve;2=king_pt;3=pub), '
                      'x(W0 or ordinal), virial, df_cont, df_mc, df_mc_err, '
                      'nbody, censored, valid', comments='')

    from plot_df_figures import plot_fig10, plot_fig11
    plot_fig10(OUTDIR + 'fig10_fbound_curves.csv', OUTDIR + 'fig10_fbound_curves')
    plot_fig11(OUTDIR + 'fig11_plotdata.csv', with_mc=False,
               out=OUTDIR + 'fig11_df_vs_virial_threshold')
    plot_fig11(OUTDIR + 'fig11_plotdata.csv', with_mc=True,
               out=OUTDIR + 'fig11b_thresholds_with_mc')
    w_eq = {lab: xo for lab, xo in _pub_ord.items()}
    print("\n  published families in Fig. 11 (ordinal x positions):")
    for lab, we in w_eq.items():
        print(f"    {lab.replace('$','').replace(chr(92)+'gamma','g'):<16}"
              f"plotted at x={we:.1f}, SFE_crit(DF)={pub_thresholds[lab]:.4f}")
    if mc_pub_path is None:
        print("  (mc_thresholds_published.csv not found -- Fig. 11b shows MC "
              "points for the King family only)")

    diag_cols = np.array([[e, float(v)] for e, v in crit_diag])
    np.savetxt(OUTDIR + 'df_threshold_summary.csv',
               np.column_stack([crit_rows, diag_cols]), fmt='%.6f',
               delimiter=', ', header='W0, SFE_crit_DF, worst_err, valid',
               comments='')
    n_bad = int((diag_cols[:, 1] == 0.0).sum())
    if n_bad:
        print(f"\n  ** {n_bad}/{len(crit_diag)} King SFE_crit_DF values in "
              f"df_threshold_summary.csv failed the ERR_TOL={ERR_TOL:.0%} "
              "reconstruction check (valid=0) -- do not quote them without "
              "checking worst_err in that column. **")
    print("\nFigs 10-11 + table done.")


if __name__ == '__main__':
    main()